module.exports.adjectives = [
    'Roasted',
    'Black',
    'Smooth',
    'Smoky',
    'Velvety',
    'Creamy',
    'Toasty',
    'French',
    'American',
    'Venice',
    'Natural',
    'Traditional',
    'Foamy',
    'Heart Attack',
    '7-eleven',
    'Walmart',
    'Never Fresh',
    'Watery',
    'Just Ok',
    'I\'ve Had Better',
    'You\'ll Never Have Better',
    'We\'ll Pay You To Eat Here'
]

module.exports.nouns = [
    'Vanilla Cafe',
    'Moka Cafe',
    'Nutmeg Cafe',
    'Chai Latte',
    'Latte Corner',
    'Espresso Cafe',
    'Aged Cafe',
    'Fermented Coffee Cafe',
    'Lactose-free Cofee Cafe',
    'Dream Cafe',
    'Cheap Cofee Cafe',
    'Premium Coffee Cafe',
    'Too Expensive For You Cafe',
    'Late Night Cafe',
    'Fertilized Coffee Cafe',
    'Day Old Cafe',
    'Canadian Cafe',
    'Caffeine Overdose Cafe',
    'Redbull Coffee Cafe',
    'Triple Espresso Shot Cafe',
    'Hangover Cafe',
    'This Name Is Too Long Cafe',
    'Donald Trump Cafe',
    'Writer\'s\ Block Cafe'
]

module.exports.collections = [
    '62334021',
    '8331835',
    '584433',
    '9787713',
    '11288659',
    '5045180',
    '4794086',
    '40914537',
    '1625008',
    '2248881'
]

module.exports.cloud = [
    'abdullah-oguk-qCrocisvGwc-unsplash_kga9k6',
    'alaksiej-carankievic-XXigdb3WMmA-unsplash_r8vv6a',
    'alexandre-brondino-p-OEpOwn--U-unsplash_ugvpu8',
    'aleksander-sadowski-dlOdly8vh4s-unsplash_w95whs',
    'christie-kim-nB9zV8K5jl8-unsplash_uvxwtg',
    'andriyko-podilnyk-bdmdX_XMcV4-unsplash_u4p7gy',
    'arpad-spodni-kF0fXa7GTj0-unsplash_i4tgak',
    'angelina-korolchak-rrlqc68yuaU-unsplash_dtdx6e',
    'ceyda-ciftci-oaI3Nhngkk8-unsplash_njf1s2',
    'irena-carpaccio-Sf9zr6rmSGI-unsplash_abplqo',
    'jacek-dylag-PR-B3hhcOZY-unsplash_ozhmpw',
    'doug-greenman-Tlb8Xw5_qWk-unsplash_mqfalw',
    'florencia-viadana-mI61X5I-jKQ-unsplash_a9wvz9',
    'grace-hazell-c7gdgLcqmEk-unsplash_fc1wsy',
    'jonny-gios-cHdvSYDK75E-unsplash_umkgjy',
    'dominic-dreier-twR54xVerrI-unsplash_ynn88i',
    'gabriella-clare-marino-gz95RnoDdrE-unsplash_abobhf',
    'hyosun-rosy-ko-23dFj4fMPnc-unsplash_gnxwx9',
    'kazuo-ota-wm0AMjFwY00-unsplash_x9muqr',
    'kris-atomic-3b2tADGAWnU-unsplash_m7xzsa',
    'laurens-r-m-d-Vg191w4OkUs-unsplash_a7r7z0',
    'klara-kulikova-yjQDnOhGE34-unsplash_bxv5i3',
    'kwon-junho-BY-qrdWlvDY-unsplash_mbcbpb',
    'kayleigh-harrington-yhn4okt6ci0-unsplash_jspahv',
    'katie-luka--ARcdtAp7a8-unsplash_ml58c8',
    'juli-kosolapova-q_jKuy-cURg-unsplash_kpyuww',
    'joshua-rodriguez-f7zm5TDOi4g-unsplash_upxxdq',
    'miguel-torres-fI9Hg6xSJE0-unsplash_yyt6m1',
    'matt-seymour-zUqOgbUf-G0-unsplash_dtjpe5',
    'mar-ko-psR1Ee51NIs-unsplash_kataie',
    'marika-pamp-4c7H6AjzxqE-unsplash_gmnygj',
    'mert-aydemir-Bpewe-_9Aok-unsplash_qj8n6y',
    'mateusz-majewski-W2CQOjjSJZM-unsplash_prvadm',
    'lorenzo-mitil-Fddx0ZncDX8-unsplash_gm5wqg',
    'nathan-dumlao-pJllO6r0pKo-unsplash_ulzfp4',
    'nathan-dumlao-g8gOnhMRckw-unsplash_mw05dn',
    'oliver-rouse-ma0eUZgMmYw-unsplash_hw4tv8',
    'robinson-greig-0xWupX0DUxQ-unsplash_kpkvgn',
    'rizky-subagja--zYjvefgc2U-unsplash_pzxjdd',
    'palemartin1-AAGCJ_OMPCk-unsplash_a5nniu',
    'nicolas-j-leclercq-dSdGjecqhKA-unsplash_lsf4wb',
    'patrick-schneider-Q2zrp_7KmNI-unsplash_tshx4b',
    'priyadarshini-maity-uInU2zkSJPQ-unsplash_nak7lr',
    'raychan-Kr1-Ew4bhSE-unsplash_fcauuy',
    'nathan-dumlao-pnmRtTHWqDM-unsplash_m7u1xp',
    'tomas-jasovsky-d5SZqLkpIrY-unsplash_z9v2zq',
    'toa-heftiba-TwtUYtDOv6w-unsplash_ndn9ms',
    'saad-sharif-vRfuN5GAx5k-unsplash_racpk8',
    'veronika-jorjobert-8OABb3PHwmg-unsplash_osq7zm',
    'sabrina-mazzeo-nuTE2cjR1xQ-unsplash_debnl7',
    'stephanie-mccabe-Yr5kaJbOm_g-unsplash_zsrrxd',
    'taewoo-kim-3PmIQkvJ5bo-unsplash_v8mcp9',
    'tom-chen-z1R3zCepJWQ-unsplash_lho6ka',
    'seemi-samuel-4qJdtfJ2MmQ-unsplash_qpu9oo',
    'yunming-wang-D2t5MVDTLs0-unsplash_efsq9x',
    'zoe-3hs4xso-4KM-unsplash_htobzn'
]